name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is not "main"

permissions:
  contents: write  # Required to allow GitHub Actions to push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Build Web
        run: |
          cd apps/web
          npm install
          npm run build

      - name: Build rtl-react-hooks
        run: |
          cd docs/rtl-hooks-docs
          npm install
          npm run build

      - name: Prepare gh-pages directory
        run: |
          rm -rf gh-pages-temp
          mkdir -p gh-pages-temp/web
          cp -r apps/web/dist/. gh-pages-temp/web/
          mkdir -p gh-pages-temp/rtl-hooks-docs
          cp -r docs/rtl-hooks-docs/build/. gh-pages-temp/rtl-hooks-docs/
          touch gh-pages-temp/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-temp
